### PR TITLE
Added function list_hosts_by_cluster()

### PR DESCRIPTION
**Pull request by mpmoers**
This function will list each cluster in the vcenter and the hosts in that cluster (if any). If a cluster name is passed in, only hosts in that cluster are listed.

### CODE REVIEW

**Comment by nmadhok** [comment]
@mpmoers Can you rebase, since this has merge conflicts? You probably forgot to sync your fork with mine which caused this.

**Comment by mpmoers** [comment]
Had to fix the merge errors caused by adding the functions written by @rmgoodberlet. Should be good to merge now

**Comment by mpmoers** [comment]
Added a similar function list_hosts_by_datacenter() which lists all hosts in all datacenters or all hosts in a specified datacenter

**Comment by nmadhok** [comment]
@mpmoers Merged. Thanks!

**Pull request merged**
